eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
server:
  port: 5555
spring:
  application:
    name: service-zuul
zuul:
  routes:
    article:
      path: /article/**
      serviceId: article
    order:
      path: /order/**
      serviceId: order